== Overview

Use this config to port trainings built underOpen Training Initiative.
This works only for OSP infrastructure.

This config is based on *Three Tier App* _config_  

Copy your custom heat template as `configs/open-training-novelloshell/files/cloud_providers/osp_cloud_template_master.j2`

== Supported Cloud Providers

* OpenStack 

TODO: Review below and discard unwated text.

== Review the Env_Type variable file

The link:./env_vars.yml[./env_vars.yml] file contains all the variables you need to define to control the deployment of your environment.

This includes the ability to:

* Change the number of machines deployed
* Changed the operating system image (e.g. Ansible AMI or similar)
* Change the tags carried by any instances
* Change the base packages installed 
* Change/set the `ansible_user` and `remote_user`

These can be over-ridden at `ansible-playbook` runtime via `-e` options or perhaps more compactly by overriding vars in your own var file and invoking via `-e @my_env_vars.yml`

For further information on customizing images consult the link:../../../docs/Creating_a_config.adoc[Creating a Config Guide] 

== Deploying the Three Tier App Config

You can deploy this config by running the following command from the `ansible`
directory. You will have to provide credentials and adjust settings to your own
environment.

`ansible-playbook -e @configs/three-tier-app/sample_vars.yml main.yml`

=== To Delete an environment
----

ansible-playbook -e @configs/three-tier-app/sample_vars.yml \ 
  configs/three-tier-app/destroy_env.yml 

----




