---
ansible_user: cloud-user
remote_user: cloud-user

chomped_zone_internal_dns: "example.com"

cloud_provider: osp
student_name: lab-user
osp_cluster_dns_server: ddns01.opentlc.com
use_dynamic_dns: true
osp_project_create: true

####  Instance flavor  ##
__instance_type: 2c4g30d
####  Image id        ##
__image: rhel-server-7.7-update-2

