- name: Step 005 Post Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Step 005 Post Software"

- name: Step lab post software deployment
  hosts: bastions
  become: yes
  tags:
    - bastion_post_software
  tasks:
    - name: Create control-user
      include_role:
        name: control-user

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
